#!/usr/bin/env bash
# Build the `openvla-probe` conda environment used by the OpenVLA embedding
# extraction and visualization scripts.
#
# The environment is created in project space (not $HOME, which has a 28 GB
# quota) and registered via ~/.condarc so `conda activate openvla-probe` works
# by name, which is what the wrapper scripts expect.
#
# Pinned per openvla-probe/README.md: torch 2.2.0, transformers 4.40.1,
# tokenizers 0.19.1, timm 0.9.10. flash-attn is intentionally skipped — it needs
# a long nvcc build and get_vla() falls back to sdpa attention cleanly.
#
# TensorFlow is installed CPU-only. openvla_utils imports it unconditionally but
# only uses tf.image for center-cropping, so the GPU build would just contend
# with torch for VRAM.
#
# Usage (login node, ~20-30 min):
#   bash scripts/setup_openvla_probe_env.sh

# Note: no `set -u`. The cluster's anaconda module ships a deactivate hook
# (qt-main_deactivate.sh) that dereferences an unset variable, which aborts the
# script the moment `conda activate` runs under nounset.
set -eo pipefail

ENV_ROOT="/cluster/tufts/hrilab/tdugga02/envs"
ENV_NAME="openvla-probe"
ENV_PREFIX="$ENV_ROOT/$ENV_NAME"
PKGS_DIR="/cluster/tufts/hrilab/tdugga02/.conda-pkgs"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PROBE_DIR="$REPO_DIR/openvla-probe"

mkdir -p "$ENV_ROOT" "$PKGS_DIR"

# ── Register project-space env/pkg dirs so `conda activate openvla-probe` resolves ──
if [[ ! -f "$HOME/.condarc" ]] || ! grep -q "$ENV_ROOT" "$HOME/.condarc" 2>/dev/null; then
    echo "[*] Writing ~/.condarc (envs_dirs -> $ENV_ROOT)"
    cat >> "$HOME/.condarc" <<EOF
envs_dirs:
  - $ENV_ROOT
pkgs_dirs:
  - $PKGS_DIR
EOF
fi

module load anaconda/2025.06.0
eval "$(conda shell.bash hook)"

if [[ -d "$ENV_PREFIX" ]]; then
    echo "[*] Environment already exists at $ENV_PREFIX — reusing."
else
    echo "[*] Creating conda env at $ENV_PREFIX (python 3.10)"
    # conda-forge only, with --override-channels: the cluster's anaconda module
    # defaults to repo.anaconda.com, whose Terms of Service must be explicitly
    # accepted before any package can be pulled. Everything we need is on
    # conda-forge, which carries no such gate.
    conda create -p "$ENV_PREFIX" python=3.10 -y \
        -c conda-forge --override-channels
fi

conda activate "$ENV_PREFIX"

echo "[*] python: $(which python)  ($(python --version 2>&1))"

# Keep pip's cache off $HOME too.
export PIP_CACHE_DIR="/cluster/tufts/hrilab/tdugga02/.pip-cache"
mkdir -p "$PIP_CACHE_DIR"

# ── PyTorch 2.2.0 / cu121 ──
# cu121 covers every GPU on this cluster: a100 (sm_80), l40s (sm_89), h200 (sm_90).
echo "[*] Installing torch 2.2.0 (cu121)"
pip install --no-input \
    torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 \
    --index-url https://download.pytorch.org/whl/cu121

# ── openvla-probe package, without its dependency closure ──
# `pip install -e .` would drag in tensorflow (GPU), tensorflow_graphics, and
# dlimp — all training-data-pipeline deps that embedding extraction never
# touches, and all frequent sources of install failures. We install the package
# for its import path only, then add the runtime deps explicitly below.
echo "[*] Installing openvla-probe (editable, no deps)"
pip install --no-input --no-deps -e "$PROBE_DIR"

# ── Runtime deps actually reached by get_openvla_vlm_embeds.py ──
#   transformers/tokenizers/timm : pinned by the README
#   tensorflow-cpu               : imported at module load by openvla_utils
#   numpy<2                      : transformers 4.40 and TF 2.15 both predate numpy 2
#   scikit-learn/matplotlib      : used by visualize_vlm_embds.py
echo "[*] Installing runtime dependencies"
pip install --no-input \
    "transformers==4.40.1" \
    "tokenizers==0.19.1" \
    "timm==0.9.10" \
    "accelerate>=0.25.0" \
    "huggingface_hub" \
    "safetensors" \
    "sentencepiece==0.1.99" \
    "tensorflow-cpu==2.15.0" \
    "numpy<2" \
    "pillow" \
    "scikit-learn" \
    "matplotlib" \
    "draccus==0.8.0" \
    "einops" \
    "rich" \
    "protobuf" \
    "jsonlines" \
    "json-numpy"

# ── RLDS data-pipeline deps, needed only to satisfy imports ──
# prismatic/__init__.py eagerly imports the VLA training stack, which reaches
# prismatic.vla.datasets.rlds and thus dlimp + tensorflow_datasets. Embedding
# extraction never builds a dataset, but the import must still resolve.
# dlimp goes in with --no-deps: its requirements would pull the GPU TensorFlow
# build back in on top of the CPU one we just installed.
# tensorflow-metadata is pinned because tfds 4.9.3 does not cap it: the current
# release ships _pb2 modules generated by protoc 5.x, which fail to import
# against the protobuf 4.x that TensorFlow 2.15 requires.
echo "[*] Installing RLDS import-time dependencies"
pip install --no-input "tensorflow_datasets==4.9.3" "tensorflow-metadata==1.15.0"
pip install --no-input --no-deps "git+https://github.com/moojink/dlimp_openvla"
# tensorflow_graphics reaches the import chain via oxe/utils/droid_utils.py.
# --no-deps keeps its heavy extras (OpenEXR, trimesh) out; only the pure-TF
# geometry.transformation module is ever touched.
pip install --no-input --no-deps "tensorflow_graphics==2021.12.3"

echo ""
echo "[*] Verifying imports"
python - <<'PY'
import torch, transformers, timm, tokenizers
import tensorflow as tf
import sklearn, matplotlib, numpy as np
print(f"  torch        {torch.__version__}   cuda_available={torch.cuda.is_available()}")
print(f"  transformers {transformers.__version__}")
print(f"  tokenizers   {tokenizers.__version__}")
print(f"  timm         {timm.__version__}")
print(f"  tensorflow   {tf.__version__}")
print(f"  numpy        {np.__version__}")
print(f"  sklearn      {sklearn.__version__}")
PY

echo ""
echo "[*] Verifying openvla-probe imports resolve"
python - <<PY
import sys
sys.path.insert(0, "$PROBE_DIR")
from prismatic.extern.hf.modeling_prismatic import OpenVLAForActionPrediction
from prismatic.models.backbones.vision.dinosiglip_vit import DinoSigLIPViTBackbone
from experiments.robot.openvla_utils import get_vla, get_processor
print("  openvla-probe imports OK")
PY

echo ""
echo "Done. Activate with:"
echo "  module load anaconda/2025.06.0 && conda activate $ENV_NAME"
